// <auto-generated />
using System;
using System.Collections.Generic;
using LiventCord.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiventCord.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301010219_addPendingAttachments")]
    partial class addPendingAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Discriminator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Nickname");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("Nickname", "Value")
                        .IsUnique();

                    b.ToTable("Discriminator", (string)null);
                });

            modelBuilder.Entity("FileBase", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("FileId");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("Content");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Extension");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("GuildId");

                    b.HasKey("FileId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("FileBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GuildInvite", b =>
                {
                    b.Property<string>("InviteId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteChannelId")
                        .HasColumnType("text");

                    b.HasKey("InviteId");

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("LiventCord.Models.Attachment", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsImageFile")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsProxyFile")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVideoFile")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.HasIndex("MessageId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("LiventCord.Models.Channel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("ChannelId");

                    b.Property<string>("ChannelDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ChannelDescription");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ChannelName");

                    b.Property<int>("ChannelVersion")
                        .HasColumnType("integer")
                        .HasColumnName("channel_version");

                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("GuildId");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool>("IsTextChannel")
                        .HasColumnType("boolean")
                        .HasColumnName("IsTextChannel");

                    b.Property<DateTime?>("LastReadDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastReadDateTime");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<string>("RecipientId")
                        .HasColumnType("text")
                        .HasColumnName("recipient_id");

                    b.HasKey("ChannelId");

                    b.HasIndex("GuildId");

                    b.HasIndex("ChannelId", "GuildId");

                    b.ToTable("Channel", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.ChannelPinnedMessage", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinnedByUserId")
                        .HasColumnType("text");

                    b.HasKey("ChannelId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("ChannelPinnedMessage", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.Friend", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.Property<string>("FriendId")
                        .HasColumnType("text")
                        .HasColumnName("FriendId");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("UserId", "FriendId");

                    b.ToTable("Friend", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.Guild", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("GuildId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("GuildName");

                    b.Property<bool>("IsGuildUploadedImg")
                        .HasColumnType("boolean")
                        .HasColumnName("IsGuildUploadedImg");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OwnerId");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("Region");

                    b.Property<string>("RootChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RootChannel");

                    b.Property<string>("Settings")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Settings");

                    b.HasKey("GuildId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Guild", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.GuildMember", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("MemberId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "MemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("UserId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("LiventCord.Models.GuildPermissions", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GuildPermissions", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.Message", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsSystemMessage")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEdited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<string>("ReactionEmojisIds")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ReplyToId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.HasIndex("ChannelId", "Date", "MessageId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.PendingAttachment", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<bool>("Claimed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.ToTable("PendingAttachments");
                });

            modelBuilder.Entity("LiventCord.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.Property<int>("Bot")
                        .HasColumnType("integer")
                        .HasColumnName("bot");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsGoogleUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_google_user");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Password");

                    b.Property<string>("SocialMediaLinks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("social_media_links");

                    b.Property<int>("Verified")
                        .HasColumnType("integer")
                        .HasColumnName("verified");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.UserChannel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastReadDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("UserChannel", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.UserDm", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<string>("FriendId")
                        .HasColumnType("text")
                        .HasColumnName("friend_id")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDm", (string)null);
                });

            modelBuilder.Entity("MediaUrl", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "fileName");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "fileSize");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "height");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isImage");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isVideo");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "width");

                    b.HasKey("Url");

                    b.ToTable("MediaUrls", (string)null);
                });

            modelBuilder.Entity("MessageUrl", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<List<string>>("Urls")
                        .HasColumnType("text[]");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("MessageUrls");
                });

            modelBuilder.Entity("UrlMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinnerUserId")
                        .HasColumnType("text");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UrlMetadata");

                    b.HasDiscriminator().HasValue("UrlMetadata");
                });

            modelBuilder.Entity("AttachmentFile", b =>
                {
                    b.HasBaseType("FileBase");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ChannelId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.ToTable("AttachmentFile", (string)null);
                });

            modelBuilder.Entity("EmojiFile", b =>
                {
                    b.HasBaseType("FileBase");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("EmojiFile", (string)null);
                });

            modelBuilder.Entity("GuildFile", b =>
                {
                    b.HasBaseType("FileBase");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildFile", (string)null);
                });

            modelBuilder.Entity("ProfileFile", b =>
                {
                    b.HasBaseType("FileBase");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileFile", (string)null);
                });

            modelBuilder.Entity("LiventCord.Models.Attachment", b =>
                {
                    b.HasOne("LiventCord.Models.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LiventCord.Models.Channel", b =>
                {
                    b.HasOne("LiventCord.Models.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("LiventCord.Models.ChannelPinnedMessage", b =>
                {
                    b.HasOne("LiventCord.Models.Channel", "Channel")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.Message", "Message")
                        .WithMany("PinnedInChannels")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LiventCord.Models.GuildMember", b =>
                {
                    b.HasOne("LiventCord.Models.Guild", "Guild")
                        .WithMany("GuildMembers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.User", null)
                        .WithMany("GuildUsers")
                        .HasForeignKey("UserId");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiventCord.Models.GuildPermissions", b =>
                {
                    b.HasOne("LiventCord.Models.Guild", "Guild")
                        .WithMany("GuildPermissions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.User", "User")
                        .WithMany("GuildPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiventCord.Models.Message", b =>
                {
                    b.HasOne("LiventCord.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Embed", "Embeds", b1 =>
                        {
                            b1.Property<string>("MessageId")
                                .HasColumnType("text");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<int?>("Color")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(8421504);

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Fields")
                                .IsRequired()
                                .HasColumnType("json");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("Rich");

                            b1.Property<string>("Url")
                                .HasColumnType("text");

                            b1.HasKey("MessageId", "Id");

                            b1.ToTable("Embed");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");

                            b1.OwnsOne("EmbedAuthor", "Author", b2 =>
                                {
                                    b2.Property<string>("EmbedMessageId")
                                        .HasColumnType("text");

                                    b2.Property<string>("EmbedId")
                                        .HasColumnType("text");

                                    b2.Property<string>("IconUrl")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Url")
                                        .HasColumnType("text");

                                    b2.HasKey("EmbedMessageId", "EmbedId");

                                    b2.ToTable("Embed");

                                    b2.WithOwner()
                                        .HasForeignKey("EmbedMessageId", "EmbedId");
                                });

                            b1.OwnsOne("EmbedFooter", "Footer", b2 =>
                                {
                                    b2.Property<string>("EmbedMessageId")
                                        .HasColumnType("text");

                                    b2.Property<string>("EmbedId")
                                        .HasColumnType("text");

                                    b2.Property<string>("IconUrl")
                                        .HasColumnType("text");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("EmbedMessageId", "EmbedId");

                                    b2.ToTable("Embed");

                                    b2.WithOwner()
                                        .HasForeignKey("EmbedMessageId", "EmbedId");
                                });

                            b1.OwnsOne("EmbedImage", "Image", b2 =>
                                {
                                    b2.Property<string>("EmbedMessageId")
                                        .HasColumnType("text");

                                    b2.Property<string>("EmbedId")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Height")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ProxyUrl")
                                        .HasColumnType("text");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int?>("Width")
                                        .HasColumnType("integer");

                                    b2.HasKey("EmbedMessageId", "EmbedId");

                                    b2.ToTable("Embed");

                                    b2.WithOwner()
                                        .HasForeignKey("EmbedMessageId", "EmbedId");
                                });

                            b1.OwnsOne("EmbedThumbnail", "Thumbnail", b2 =>
                                {
                                    b2.Property<string>("EmbedMessageId")
                                        .HasColumnType("text");

                                    b2.Property<string>("EmbedId")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Height")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ProxyUrl")
                                        .HasColumnType("text");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int?>("Width")
                                        .HasColumnType("integer");

                                    b2.HasKey("EmbedMessageId", "EmbedId");

                                    b2.ToTable("Embed");

                                    b2.WithOwner()
                                        .HasForeignKey("EmbedMessageId", "EmbedId");
                                });

                            b1.OwnsOne("EmbedVideo", "Video", b2 =>
                                {
                                    b2.Property<string>("EmbedMessageId")
                                        .HasColumnType("text");

                                    b2.Property<string>("EmbedId")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Height")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ProxyUrl")
                                        .HasColumnType("text");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int?>("Width")
                                        .HasColumnType("integer");

                                    b2.HasKey("EmbedMessageId", "EmbedId");

                                    b2.ToTable("Embed");

                                    b2.WithOwner()
                                        .HasForeignKey("EmbedMessageId", "EmbedId");
                                });

                            b1.Navigation("Author");

                            b1.Navigation("Footer");

                            b1.Navigation("Image");

                            b1.Navigation("Thumbnail");

                            b1.Navigation("Video");
                        });

                    b.Navigation("Channel");

                    b.Navigation("Embeds");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiventCord.Models.UserChannel", b =>
                {
                    b.HasOne("LiventCord.Models.Channel", "Channel")
                        .WithMany("UserChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.User", "User")
                        .WithMany("UserChannels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiventCord.Models.UserDm", b =>
                {
                    b.HasOne("LiventCord.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiventCord.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttachmentFile", b =>
                {
                    b.HasOne("FileBase", null)
                        .WithOne()
                        .HasForeignKey("AttachmentFile", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmojiFile", b =>
                {
                    b.HasOne("FileBase", null)
                        .WithOne()
                        .HasForeignKey("EmojiFile", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildFile", b =>
                {
                    b.HasOne("FileBase", null)
                        .WithOne()
                        .HasForeignKey("GuildFile", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileFile", b =>
                {
                    b.HasOne("FileBase", null)
                        .WithOne()
                        .HasForeignKey("ProfileFile", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiventCord.Models.Channel", b =>
                {
                    b.Navigation("PinnedMessages");

                    b.Navigation("UserChannels");
                });

            modelBuilder.Entity("LiventCord.Models.Guild", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("GuildMembers");

                    b.Navigation("GuildPermissions");
                });

            modelBuilder.Entity("LiventCord.Models.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("PinnedInChannels");
                });

            modelBuilder.Entity("LiventCord.Models.User", b =>
                {
                    b.Navigation("GuildPermissions");

                    b.Navigation("GuildUsers");

                    b.Navigation("UserChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
