name: "TypeScript CodeQL Analysis"

on:
  push:
    branches: [ "main" ]
    paths:
      - "web/**"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '17 1 * * 2'

jobs:
  analyze:
    name: Analyze TypeScript Code

    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: none

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - if: matrix.build-mode == 'manual'
      shell: bash
      run: |
        echo 'Replace with build commands if needed'
        exit 1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
