name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the release"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v2
        with:
          repository: liventcord/LiventCord
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Working Directory to src
        run: cd src

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: src

      - name: Publish the Application
        run: dotnet publish -c Release -o ./publish
        working-directory: src

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/publish
          asset_name: liventcord-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
