services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Properties/appsettings.json:/app/Properties/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production} 
    entrypoint: ["./LiventCord"]
