version: "3.9"

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./Properties/appsettings.json:/app/Properties/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production} 
    networks:
      - shared_network
    extra_hosts:
      - "localhost:host-gateway"

  go-ws-api:
    build:
      context: ./server/go-ws-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared_network
    extra_hosts:
      - "localhost:host-gateway"

  go-proxy-api:
    build:
      context: ./server/proxy-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - shared_network
    extra_hosts:
      - "localhost:host-gateway"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - shared_network
    extra_hosts:
      - "localhost:host-gateway"

networks:
  shared_network:
    driver: bridge
