name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v2
        with:
          repository: liventcord/LiventCord
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Working Directory to src
        run: cd src

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: src

      - name: Publish the Application
        run: dotnet publish -c Release -o ./publish
        working-directory: src

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: liventcord-release
          path: ./src/publish
