name: "C# CodeQL Analysis"

on:
  push:
    branches: [ "main" ]
    paths:
      - "server/src/**"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * 2'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      server_changed: ${{ steps.filter.outputs.server }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect changes in server/src
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            server:
              - 'server/src/**'

  analyze:
    name: Analyze C# Code
    needs: filter
    runs-on: ubuntu-latest
    if: needs.filter.outputs.server_changed == 'true'
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: csharp
            build-mode: autobuild

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - if: matrix.build-mode == 'manual'
        shell: bash
        run: |
          echo 'Replace with build commands if needed'
          exit 1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
